windows: test.cpp mypasscrack.cpp
	g++ test.cpp mypasscrack.cpp -std=c++17 -o testWin10_x86-64.o
	echo "Compiled test.cpp for WSL"

mac: test.cpp mypasscrack.cpp
	g++ test.cpp mypasscrack.cpp -std=c++17 -o testOSX_x86-64.o
	echo "Compiled test.cpp for Mac"